#
# Makefile for the Omnivision TCM touchscreen driver.
#

# Each configuration option enables a list of files.

#obj-$(CONFIG_TOUCHSCREEN_OMNIVISION_TCM_I2C) += omnivision_tcm_i2c.o
#obj-$(CONFIG_TOUCHSCREEN_OMNIVISION_TCM_CORE) += omnivision_tcm_core_module.o
#omnivision_tcm_core_module-objs := omnivision_tcm_core.o omnivision_tcm_touch.o

obj-y	+= omnivision_tcm_i2c.o
obj-y	+= omnivision_tcm_core.o
obj-y	+= omnivision_tcm_touch.o
